name: 1.0$(Rev:.r)

# simplified trigger (implied branch)
trigger:

- master

# equivalents trigger
# trigger:
#  branches:
#    include:
#    - main

variables:
  name: John

pool: TestPool

jobs:

- job: helloworld
  steps:
    - checkout: self
    - script: echo "Hello, $(name)"